name = "Coils"
uuid = "ab2e6513-8582-4355-97c5-84ec58029ba0"
authors = ["Bodo.Kaiser"]
version = "0.1.1"

[deps]
Elliptic = "b305315f-e792-5b7a-8f41-49f472929428"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"


[compat]
Elliptic = "1"
PhysicalConstants = "0.2"
Unitful = "1.12"
julia = "1.8, 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
